# Generated by Django 4.2.23 on 2025-09-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feirantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feira',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='telefone',
        ),
    ]
