# Generated by Django 4.2.23 on 2025-09-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feirantes', '0002_remove_feira_descricao_remove_feira_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feirante',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='feirante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feirante', to=settings.AUTH_USER_MODEL),
        ),
    ]
