# Generated by Django 4.2.23 on 2025-09-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feirantes', '0003_alter_feirante_cpf_alter_feirante_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feirante',
            name='feiras',
            field=models.ManyToManyField(blank=True, help_text='Feiras onde o feirante participa', related_name='feirantes', to='feirantes.feira'),
        ),
    ]
