# Generated by Django 4.2.23 on 2025-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feirantes', '0004_alter_feirante_feiras'),
    ]

    operations = [
        migrations.AddField(
            model_name='feirante',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
