# Generated by Django 4.2.23 on 2025-10-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feirantes', '0005_feirante_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feirante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('nota', models.IntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('feirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='feirantes.feirante')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('feirante', 'email', 'cpf')},
            },
        ),
    ]
