# Generated by Django 4.2.23 on 2025-10-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feirantes', '0006_alter_feirante_email_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario_cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, verbose_name='CPF do Usuário'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Usuário'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario_nome',
            field=models.CharField(default='Anônimo', max_length=100, verbose_name='Nome do Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, default='', verbose_name='Comentário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Nota'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('feirante', 'usuario_email', 'usuario_cpf')},
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='email',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nome',
        ),
    ]
